# Generated by Django 5.1.7 on 2025-04-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_attendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='reg_number',
        ),
    ]
