# Generated by Django 5.1.7 on 2025-04-07 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_registration_number_student_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='reg_number',
            new_name='registration_number',
        ),
    ]
