# Generated by Django 5.1.7 on 2025-04-07 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_reg_number_student_registration_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='registration_number',
            new_name='reg_number',
        ),
    ]
